account/urls.py
from django.urls import path
from . import views
from account.views import RegisterUserView

urlpatterns = [
    path('register/' , RegisterUserView.as_view() , name = 'register'),
    
]

audiotracks/urls.py
from django.conf.urls import url

from audiotracks import feeds
from audiotracks import views


urlpatterns = [
    url(r"^$", views.index, name="audiotracks"),
    url(r"^(?P<page_number>\d+)/?$", views.index, name="audiotracks"),
    url(r"^track/(?P<track_slug>.*)$", views.track_detail,
        name="track_detail"),
    url(r"^upload", views.upload_track, name="upload_track"),
    url(r"^edit/(?P<track_id>.+)", views.edit_track, name="edit_track"),
    url(r"^confirm_delete/(?P<track_id>\d+)$",
        views.confirm_delete_track, name="confirm_delete_track"),
    url(r"^delete$", views.delete_track, name="delete_track"),
    url(r"^tracks$", views.user_index, name="user_index"),
    url(r"^tracks/(?P<page_number>\d)/?$", views.user_index,
        name="user_index"),
    url(r"^feed/?$", feeds.choose_feed, name="tracks_feed"),
    url(r"^player.js$", views.player_script, name="player_script"),
    url(r"^m3u/?$", views.m3u, name="m3u"),
]

musicON/urls.py
from django.contrib import admin
from django.urls import path , include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('account/', include('account.urls')),
    path('firstpage/', include('firstpage.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('loginsys.urls')),
     # Here we mount the app under /music. Feel free to use something else
    path('music/', include("audiotracks.urls")),
    # Some URLs require a Django username
    path("(?P<username>[\w\._-]+)/music", include("audiotracks.urls")),

]

audiotracks/models.py
import os
import mimetypes

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ImproperlyConfigured
try:
    from django.apps import apps as django_apps
except ImportError:
    django_apps = None


from .thumbs import ImageWithThumbsField


def slugify_uniquely(value, obj, slugfield="slug"):
    suffix = 1
    potential = base = slugify(value)
    filter_params = {}
    filter_params['user'] = obj.user
    while True:
        if suffix > 1:
            potential = "-".join([base, str(suffix)])
        filter_params[slugfield] = potential
        obj_count = obj.__class__.objects.filter(**filter_params).count()
        if not obj_count:
            return potential[:50]
        # we hit a conflicting slug, so bump the suffix & try again
        suffix += 1


def get_upload_path(dirname, obj, filename):
    return os.path.join("audiotracks", dirname, obj.user.username, filename)


def get_images_upload_path(obj, filename):
    return get_upload_path("images", obj, filename)


def get_audio_upload_path(obj, filename):
    return get_upload_path("audio_files", obj, filename)


class AbstractTrack(models.Model):

    class Meta:
        abstract = True

    user = models.ForeignKey(User,
                             related_name="tracks",
                             blank=True,
                             null=True,
                             on_delete=models.CASCADE
                             )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    audio_file = models.FileField(
        _("Audio file"), upload_to=get_audio_upload_path)
    image = ImageWithThumbsField(
        _("Image"), upload_to=get_images_upload_path, null=True,
        blank=True, sizes=((48, 48), (200, 200)))
    title = models.CharField(_("Title"), max_length=200, null=True)
    artist = models.CharField(
        _("Artist"), max_length=200, null=True, blank=True)
    genre = models.CharField(
        _("Genre"), max_length=200, null=True, blank=True)
    date = models.CharField(_("Date"), max_length=200, null=True, blank=True)
    description = models.TextField(_("Description"), null=True, blank=True)
    slug = models.SlugField(verbose_name=_("Slug (last part of the url)"))
    _original_slug = None  # Used to detect slug change

    def __init__(self, *args, **kwargs):
        super(AbstractTrack, self).__init__(*args, **kwargs)
        self._original_slug = self.slug

    def __unicode__(self):
        return "Track '%s' uploaded by '%s'" % (self.title, self.user.username)

    def save(self, **kwargs):
        if not self.slug:
            # Automatically set initial slug
            slug_source = getattr(self, 'title') or \
                os.path.splitext(os.path.basename(self.audio_file.name))[0]
            self.slug = slugify_uniquely(slug_source, self)
        super(AbstractTrack, self).save(**kwargs)

    @property
    def mimetype(self):
        if not hasattr(self, '_mimetype'):
            self._mimetype = mimetypes.guess_type(self.audio_file.path)[0]
        return self._mimetype

    @property
    def filetype(self):
        if '/' in self.mimetype:
            type_names = {'mpeg': 'MP3', 'ogg': 'Ogg Vorbis'}
            filetype = self.mimetype.split('/')[1]
            return type_names.get(filetype, filetype)
        else:
            return self.mimetype

    @models.permalink
    def get_absolute_url(self):
        return ('audiotracks.views.track_detail',
                [self.user.username, self.slug])


class Track(AbstractTrack):

    class Meta(AbstractTrack.Meta):
        swappable = 'AUDIOTRACKS_MODEL'


def get_track_model():
    if not hasattr(get_track_model, 'result'):
        if hasattr(settings, 'AUDIOTRACKS_MODEL'):
            if django_apps:
                try:
                    get_track_model.result = django_apps.get_model(
                        settings.AUDIOTRACKS_MODEL)
                except ValueError:
                    raise ImproperlyConfigured(
                        "AUDIOTRACKS_MODEL must be of the form " +
                        "'app_label.model_name'")
                except LookupError:
                    raise ImproperlyConfigured(
                        "AUDIOTRACKS_MODEL refers to model " +
                        "'%s' that has not been installed" %
                        settings.AUTH_USER_MODEL)
            else:
                app_name, model_name = settings.AUDIOTRACKS_MODEL.split('.')
                get_track_model.result = models.get_model(app_name, model_name)
        else:
            get_track_model.result = Track
    return get_track_model.result

audiotracks/forms.py
from django import forms

from audiotracks.models import get_track_model


class TrackUploadForm(forms.ModelForm):
    class Meta:
        model = get_track_model()
        fields = ('audio_file',)


class TrackEditForm(forms.ModelForm):

    class Meta:
        model = get_track_model()
        exclude = ('user', 'created_at', 'updated_at')
        widgets = {'audio_file': forms.FileInput, 'image': forms.FileInput}

    def clean_slug(self):
        new_slug = self.cleaned_data['slug']
        if new_slug != self.instance._original_slug:
            params = {'slug': new_slug}
            params['user'] = self.instance.user
            if get_track_model().objects.filter(**params).count():
                raise forms.ValidationError("This URL is already taken.")

        return new_slug

audiotracks/views.py
import os

from django.utils.translation import ugettext
from django.contrib.auth.decorators import login_required
from django.contrib.sites.requests import RequestSite
from django.conf import settings
from django.core.files.uploadhandler import TemporaryFileUploadHandler
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import *
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import render

try:
    import mutagen
except ImportError:
    import mutagenx as mutagen  # Py3

from audiotracks.models import get_track_model
from audiotracks.forms import TrackUploadForm, TrackEditForm

METADATA_FIELDS = ('title', 'artist', 'genre', 'description', 'date')


def paginate(tracks, page_number):
    per_page = getattr(settings, 'AUDIOTRACKS_PER_PAGE', 10)
    paginator = Paginator(tracks, per_page)

    if page_number is None:
        page = paginator.page(1)
    else:
        try:
            page = paginator.page(int(page_number))
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            page = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of
            # results.
            page = paginator.page(paginator.num_pages)
    return page, page.object_list


def index(request, username=None, page_number=None):
    tracks = get_track_model().objects
    if username:
        tracks = tracks.filter(user__username=username)
    tracks = tracks.order_by('-created_at').all()
    page, tracks = paginate(tracks, page_number)
    base_path = reverse(
        'audiotracks',
        args=[username] if username is not None else [])
    return render(request,"audiotracks/latest.html", {
        'username': username, 'tracks': tracks, 'page': page,
        'base_path': base_path,
    })


def user_index(request, username, page_number=None):
    user = get_object_or_404(User, username=username)
    tracks = user.tracks.order_by('-created_at').all()
    page, tracks = paginate(tracks, page_number)
    base_path = reverse('user_index', args=[username])
    return render(request,"audiotracks/user_index.html", {
        'username': username, 'tracks': tracks, 'page': page,
        'base_path': base_path,
    })


def track_detail(request, track_slug, username=None):
    params = {'slug': track_slug}
    params['user__username'] = username
    track = get_object_or_404(get_track_model(), **params)
    return render(request,"audiotracks/detail.html",
                              {'username': username, 'track': track})


def set_temporary_file_upload_handler(request):
    # Disable in memory upload before accessing POST
    # because we need a file from which to read metadata
    request.upload_handlers = [TemporaryFileUploadHandler()]


@login_required
@csrf_exempt  # request.POST is accessed by CsrfViewMiddleware
def upload_track(request):
    set_temporary_file_upload_handler(request)
    if request.method == "POST":
        form = TrackUploadForm(request.POST, request.FILES)
        if form.is_valid():
            audio_file = request.FILES['audio_file']
            audio_file_path = audio_file.temporary_file_path()
            metadata = mutagen.File(audio_file_path, easy=True)
            track = form.save(commit=False)
            track.user = request.user
            for field in METADATA_FIELDS:
                if metadata and metadata.get(field):
                    setattr(track, field, metadata.get(field)[0])
            track.save()

            return HttpResponseRedirect(reverse('edit_track',
                                                             args=[track.id]))
    else:
        form = TrackUploadForm()
    return render(request,"audiotracks/new.html", {'form': form})


def update_audiofile_metadata(track):
    filepath = track.audio_file.path
    metadata = mutagen.File(filepath, easy=True)
    if metadata:
        for field in METADATA_FIELDS:
            try:
                metadata[field] = getattr(track, field)
            except mutagen.easyid3.EasyID3KeyError:
                pass
        metadata.save()


@login_required
def edit_track(request, track_id):
    username = request.user.username
    track = request.user.tracks.get(id=track_id)
    if request.method == "POST":
        form = TrackEditForm(request.POST, request.FILES, instance=track)
        if form.is_valid():
            track = form.save()
            update_audiofile_metadata(track)
            if 'delete_image' in request.POST:
                track.image = None
                track.save()
            messages.add_message(request, messages.INFO,
                                 ugettext('Your changes have been saved.'))
            redirect_url = reverse('user_index', args=[username])
            return HttpResponseRedirect(redirect_url)
    else:
        form = TrackEditForm(instance=track, )
    track_url_args = ['']
    track_url_args.insert(0, username)
    track_detail_url = reverse('track_detail',
                                            args=track_url_args)
    track_url_prefix = request.build_absolute_uri(track_detail_url)
    track_filename = os.path.basename(track.audio_file.name)
    return render(request,"audiotracks/edit.html", {
        'form': form,
        'track': track,
        'track_url_prefix': track_url_prefix,
        'track_filename': track_filename,
    })


@login_required
def confirm_delete_track(request, track_id):
    track = get_object_or_404(request.user.tracks, id=track_id)
    default_origin_url = reverse('user_index',
                                              args=[request.user.username])
    return render(request,"audiotracks/confirm_delete.html", {
        'track': track,
        'came_from': request.GET.get('came_from', default_origin_url)
    })


@login_required
def delete_track(request):
    track_id = request.POST.get('track_id')
    track = get_object_or_404(request.user.tracks, id=track_id)
    track.delete()
    messages.add_message(request, messages.INFO,
                         ugettext('"%s" has been deleted.') % track.title)
    return HttpResponseRedirect(request.POST.get('came_from', '/'))


class JavaScriptView(TemplateView):

    def render_to_response(self, context, **response_kwargs):
        response_kwargs['content_type'] = "application/javascript"
        return super(JavaScriptView, self).render_to_response(
            context, **response_kwargs)

player_script = JavaScriptView.as_view(template_name="audiotracks/player.js")


def m3u(request, username=None):
    tracks = get_track_model().objects
    if username:
        tracks = tracks.filter(user__username=username)
    tracks = tracks.order_by('-created_at').all()
    response = HttpResponse(content_type="audio/x-mpequrl")
    site = RequestSite(request)
    filename = "playlist-%s.m3u" % (site.name if username is None
                                    else username)
    response['Content-Disposition'] = 'attachment; filename=%s' % filename
    for track in tracks:
        url = 'http://%s/%s' % (site.domain, track.audio_file.url.strip("/"))
        response.write(url + "\n")
    return response

audiotracks/templates/audiotracks/_list_actions.html
{% load i18n %}
  <a class="btn small btn-primary" href="{% url 'edit_track' track.id %}">{% trans 'Edit' %}</a>
  <a class="btn small btn-danger" href="{% url 'confirm_delete_track' track.id %}">{% trans 'Delete' %}</a>

audiotracks/templates/audiotracks/base.html
{% load i18n %} 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>django-audiotracks example project</title>
    <style>
      label { display: block; }
      .audiotracks-edit-row { clear:both; margin-bottom: 1em; }
      .audiotracks-edit-row > div { float: left; margin-right: 1em; }
      .audiotracks-form { margin-bottom: 1em; }
      .audiotracks-delete-image-label { display: inline; }
      .messages { color: green; border: solid 1px green; padding: 0.2em; }
      .messages li { list-style: none; }
      .errorlist { color: red; list-style: none; display: inline; }
    </style>
    {% block extra_head %}{% endblock %}
  </head>
  <body>

  {% block subnav %}
      {% if user.is_authenticated %}
          <ul>
            <li><a href="{% url 'audiotracks' %}">{% trans 'Latest tracks' %}</a></li>
            <li><a href="{% url 'user_index' user.username %}">{% trans 'Your tracks' %}</a></li>
            <li><a href="{% url 'upload_track' %}">{% trans 'Upload track' %}</a></li>
          </ul>
      {% else %}
          &nbsp;
      {% endif %}
  {% endblock %}

  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  {% block body %}{% endblock %}
  {% block extra_body %}{% endblock %}
  </body>
</html>

audiotracks/templates/audiotracks/confirm_delete.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block body %}
{% if user.is_authenticated %}
<div class="audiotracks-form">
  <p>
  {% blocktrans with track.title as title %}Are you sure you want to delete "{{ title }}"? This can't be undone.{% endblocktrans %}
  </p>
  <form method="POST" action="{% url 'delete_track' %}">
    {% csrf_token %}
    <input type="hidden" name="track_id" value="{{ track.id }}">
    <input type="hidden" name="came_from" value="{{ came_from }}">
    <button class="btn btn-danger">{% trans 'Yes, delete this track' %}</button>
  </form>
</div>
{% endif %}
{% endblock %}

audiotracks/templates/audiotracks/detail.html
{% extends "audiotracks/mediaelement_base.html" %}
{% load i18n %}

{% block body %}
<div class="audiotracks-detail js-audiotracks-container">
  {% if track.image %}
  <img src="{{ track.image.url_200x200 }}" />
  {% endif %}
  {% include "audiotracks/listing_item.html" %}
  {% if track.description %}
  <div class="audiotracks-description">
    {{ track.description }}
  </div>
  {% endif %}
  <div class="audiotracks-download">
    <a class="btn btn-large btn-success" href="{{ track.audio_file.url }}">
      {% blocktrans with size=track.audio_file.size|filesizeformat  type=track.filetype %}
      Download {{ type }} file ({{size}})
      {% endblocktrans %}
    </a>
  </div>
{% if track.user == request.user %}
<p>
  <a class="btn btn-primary" href="{% url 'edit_track' track.id %}">{% trans 'Edit' %}</a>
  <a class="btn btn-danger" href="{% url 'confirm_delete_track' track.id %}">{% trans 'Delete' %}</a>
</p>
{% endif %}
</div>
{% endblock %}

audiotracks/templates/audiotracks/edit.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block body %}
{% if user.is_authenticated %}
<div class="audiotracks-form">
  <form class="form-stacked" method="POST" enctype="multipart/form-data" 
    action="{% url 'edit_track' track.id %}">
    {% csrf_token %}
    <fieldset>
      <legend>{% trans 'Edit track' %}</legend>
      {{ form.non_field_errors }}
      <div class="audiotracks-edit-row">
        {{ form.audio_file.errors }}
        <label class="top" for="id_audio_file">{{ form.audio_file.label }}</label>
        {{ form.audio_file }}
        <span class="audiotracks-edit-current-data">{{ track_filename }}</span>
      </div>
      <div class="audiotracks-edit-row">
        {{ form.image.errors }}
        <label class="top" for="id_image">{{ form.image.label }}</label>
        {{ form.image }}
        {% if track.image %}
          <img src="{{ track.image.url_48x48 }}" alt="Track image">
          <input type="checkbox" name="delete_image" value="1"
          id="delete_image">
          <label id="audiotracks-delete-image-label" for="delete_image">{% trans 'Delete image' %}</label>
        {% endif %}
      </div>
      <div class="audiotracks-edit-row">
        <div class="audiotracks-edit-half-row">
          {{ form.title.errors }}
          <label for="id_title">{{ form.title.label }}</label>
          {{ form.title }}
        </div>
        <div class="audiotracks-edit-half-row">
          {{ form.artist.errors }}
          <label for="id_artist">{{ form.artist.label }}</label>
          {{ form.artist }}
        </div>
      </div>
      <div class="audiotracks-edit-row">
        <div class="audiotracks-edit-half-row">
          {{ form.genre.errors }}
          <label for="id_genre">{{ form.genre.label }}</label>
          {{ form.genre }}
        </div>
        <div class="audiotracks-edit-half-row">
          {{ form.date.errors }}
          <label for="id_date">{{ form.date.label }}</label>
          {{ form.date }}
        </div>
      </div>
      <div class="audiotracks-edit-row">
        {{ form.tags.errors }}
        <label for="id_tags">{{ form.tags.label }}</label>
        {{ form.tags }}
      </div>
      <div class="audiotracks-edit-row">
        {{ form.description.errors }}
        <label class="top" for="id_description">{{ form.description.label }}</label>
        {{ form.description }}
      </div>
      <div id="slug" class="audiotracks-edit-row">
        {{ form.slug.errors }}
        <label for="id_slug">{{ form.slug.label }}</label>
        <div class="input-prepend">
          <span class="audiotracks-edit-current-data add-on">{{ track_url_prefix }}</span>{{ form.slug }}
        </div>
      </div>
      <p id="save-button">
      <button class="btn btn-primary">{% trans 'Save your changes' %}</button>
      </p>
    </fieldset>
  </form>
</div>
<div class="audiotracks-form" id="delete-form">
  <form action="{% url 'confirm_delete_track' track.id %}">
    <p id="delete-button">
    <button class="btn btn-danger">{% trans 'Delete this track' %}</button>
    </p>
  </form>
</div>
{% endif %}
{% endblock %}

audiotracks/templates/audiotracks/latest.html
{% extends "audiotracks/mediaelement_base.html" %}
{% load i18n %}

{% block body %}
<h1>{% trans 'Latest Tracks' %}</h1>
<a href="{% url 'tracks_feed' %}">Podcast feed</a>,
<a href="{% url 'm3u' %}">m3u playlist</a>
<ul class="audiotracks-list">
{% for track in tracks %}
    {% include "audiotracks/listing_item.html" %}
{% endfor %}
</ul>

{% include '_pagination.html' %}

{% endblock %}

audiotracks/templates/audiotracks/listing_item.html
{% load i18n %}
  <div class="audiotracks-list-entry js-audiotracks-container">
    {% if track.image %}
    <img class="track-image" src="{{ track.image.url_48x48 }}" alt="{% trans 'Track Image' %}" />
    {% endif %}
    <div class="track-details">
      <a href="{% url 'track_detail' username=track.user.username track_slug=track.slug %}">
        <p class="track-title js-audiotracks-title">
        {% if track.artist %} {{ track.artist }} &#8211; {% endif %}{{ track.title|title }}{% if track.genre %} ({{ track.genre }}){% endif %}
        </p>
      </a>
      <p class="upload-details">
        {% trans 'uploaded by' %}
        {{ track.user.username }}
        {% blocktrans with track.created_at|timesince as track_age %}{{ track_age }} ago{% endblocktrans %}
      </p>
    </div>
    <div class="player-container">
      <audio preload="none">
        <source src="{{ track.audio_file.url }}" type="{{ track.mimetype }}">
      </audio>
    </div>
    <p class="debug-info">Player type: <span class="audio-type"></span></p>
    {% if track.user == request.user %}
    <div class="audiotracks-action">
      <a href="{% url 'edit_track' track.id %}">{% trans 'Edit' %}</a>
      <a href="{% url 'confirm_delete_track' track.id %}">{% trans 'Delete' %}</a>
    </div>
    {% endif %}
  </div>

audiotracks/templates/audiotracks/mediaelement_base.html
{% extends "audiotracks/base.html" %}

{% block extra_head %}{{ block.super }}<link rel="stylesheet" href="{{ STATIC_URL }}mediaelement-2.8.2/mediaelementplayer.min.css" />{% endblock %}

{% block extra_body %}{{ block.super}}
<script>window.jQuery || document.write('<script src="{{ STATIC_URL }}mediaelement-2.8.2/jquery-1.7.2.min.js"><\/script>')</script>
<script src="{{ STATIC_URL }}mediaelement-2.8.2/mediaelement-and-player.min.js"></script>
<script src="{% url 'player_script' %}"></script>
{% endblock %}

audiotracks/templates/audiotracks/new.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block body %}
{% if user.is_authenticated %}
<form class="audiotracks-form" id="audiotracks-upload-form" 
      method="POST" enctype="multipart/form-data" action="{% url 'upload_track' %}">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans 'Upload a new track' %}</legend>
    {{ form.as_p }}
  </fieldset>
  <p>
  <button class="btn primary">{% trans 'Upload' %}</button>
  </p>
</form>
{% endif %}
{% endblock %}

audiotracks/templates/audiotracks/user_index.html
{% extends "audiotracks/mediaelement_base.html" %}
{% load i18n %}

{% block body %}
<h1>
  {% blocktrans %}Tracks from {{ username }}{% endblocktrans %}
</h1>
<a href="{% url 'tracks_feed' username %}">Podcast feed</a>,
<a href="{% url 'm3u' username %}">m3u playlist</a>
<ul class="audiotracks-list">
{% for track in tracks %}
    {% include "audiotracks/listing_item.html" %}
{% endfor %}
</ul>

{% include '_pagination.html' %}

{% endblock %}